alumnos = int(input("Cuantos alumnos tienes? "))
euro = int(input("Cuantos euros daras cada uno? "))
print("Aún quedan", euro % alumnos, "euro")
print("Qué numero", euro // alumnos, "mas vulgar")
print("Qué numero", euro / alumnos, "mas vulgar")
